/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  chzhshchSidebar: [
    'chzhshch/chzhshchintro',
    {
      type: 'category',
      label: '缠师原版',
      items: ['chzhshch/original/chzhshch001', 
              'chzhshch/original/chzhshch002', 
              'chzhshch/original/chzhshch003', 
              'chzhshch/original/chzhshch004', 
              'chzhshch/original/chzhshch005', 
              'chzhshch/original/chzhshch006',
              'chzhshch/original/chzhshch007', 
              'chzhshch/original/chzhshch008', 
              'chzhshch/original/chzhshch009', 
              'chzhshch/original/chzhshch010', 
              'chzhshch/original/chzhshch011', 
              'chzhshch/original/chzhshch012', 
              'chzhshch/original/chzhshch013', 
              'chzhshch/original/chzhshch014', 
              'chzhshch/original/chzhshch015', 
              'chzhshch/original/chzhshch016', 
              'chzhshch/original/chzhshch017', 
              'chzhshch/original/chzhshch018', 
              'chzhshch/original/chzhshch019', 
              'chzhshch/original/chzhshch020', 
              'chzhshch/original/chzhshch021', 
              'chzhshch/original/chzhshch022', 
              'chzhshch/original/chzhshch023', 
              'chzhshch/original/chzhshch024', 
              'chzhshch/original/chzhshch025', 
              'chzhshch/original/chzhshch026', 
              'chzhshch/original/chzhshch027', 
              'chzhshch/original/chzhshch028', 
              'chzhshch/original/chzhshch029', 
              'chzhshch/original/chzhshch030', 
              'chzhshch/original/chzhshch031', 
              'chzhshch/original/chzhshch032', 
              'chzhshch/original/chzhshch033', 
              'chzhshch/original/chzhshch034', 
              'chzhshch/original/chzhshch035', 
              'chzhshch/original/chzhshch036', 
              'chzhshch/original/chzhshch037', 
              'chzhshch/original/chzhshch038'],
    },
    {
      type: 'category',
      label: '无木目版',
      items: ['chzhshch/vwumumu/vchzhshch001', 
              'chzhshch/vwumumu/vchzhshch002', 
              'chzhshch/vwumumu/vchzhshch003', 
              'chzhshch/vwumumu/vchzhshch004', 
              'chzhshch/vwumumu/vchzhshch005', 
              'chzhshch/vwumumu/vchzhshch006',
              'chzhshch/vwumumu/vchzhshch007', 
              'chzhshch/vwumumu/vchzhshch008', 
              'chzhshch/vwumumu/vchzhshch009', 
              'chzhshch/vwumumu/vchzhshch010', 
              'chzhshch/vwumumu/vchzhshch011', 
              'chzhshch/vwumumu/vchzhshch012', 
              'chzhshch/vwumumu/vchzhshch013', 
              'chzhshch/vwumumu/vchzhshch014', 
              'chzhshch/vwumumu/vchzhshch015', 
              'chzhshch/vwumumu/vchzhshch016', 
              'chzhshch/vwumumu/vchzhshch017', 
              'chzhshch/vwumumu/vchzhshch018', 
              'chzhshch/vwumumu/vchzhshch019', 
              'chzhshch/vwumumu/vchzhshch020', 
              'chzhshch/vwumumu/vchzhshch021', 
              'chzhshch/vwumumu/vchzhshch022', 
              'chzhshch/vwumumu/vchzhshch023', 
              'chzhshch/vwumumu/vchzhshch024', 
              'chzhshch/vwumumu/vchzhshch025', 
              'chzhshch/vwumumu/vchzhshch026', 
              'chzhshch/vwumumu/vchzhshch027', 
              'chzhshch/vwumumu/vchzhshch028', 
              'chzhshch/vwumumu/vchzhshch029', 
              'chzhshch/vwumumu/vchzhshch030', 
              'chzhshch/vwumumu/vchzhshch031', 
              'chzhshch/vwumumu/vchzhshch032', 
              'chzhshch/vwumumu/vchzhshch033', 
              'chzhshch/vwumumu/vchzhshch034', 
              'chzhshch/vwumumu/vchzhshch035', 
              'chzhshch/vwumumu/vchzhshch036', 
              'chzhshch/vwumumu/vchzhshch037', 
              'chzhshch/vwumumu/vchzhshch038'],
      collapsible: false
    },
  ],
  bookSidebar: [
    'book/bookintro',
  ],
  otherSidebar: [
    'other/otherintro',
    'other/multiple-git-ssh',
  ],
};

module.exports = sidebars;
